### ISSUE TITLE
Move over from Uploadthing to S3

### ISSUE THREAD

**Issue by luccasmmg** [luccasmmg/t3-dataportal#3]
We want to move over the blob storage from Uploadthing to S3 mainly because of two things

- Uploadthing has a limit of 2GB per project, meaning our entire cluster of portals would only be able to store 2GB of Blob storage
- S3 has S3 Select which i think will be a good enough replacement for a datastore

# Tasks

- [ ] Create a route that supplies a pre signed S3 PUT Url
- [ ] Use that to upload groups images
- [ ] Use that to upload orgs images
- [ ] Use probably uppy to multipart upload to resources(I think a 100MB cap is good enough for now)
